### ISSUE TITLE
Move 3d.io domain to amazon route53

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-website#1]
Move 3d.io domain to amazon route53 (or a better DNS service which is not a pain with main domains in combination with heroku)

**Comment by AVGP** [comment]
The domain is now managed via Route53, but we still need to transfer the domain registration to AWS as well to fully move away from NameCheap

**Comment by AVGP** [comment]
@dburgauer did we get the transfer done?

**Comment by dburgauer** [comment]
@martin I thought we did this together. Is there something I need to still do? Never done this and don't know all that needs to be done here, please let me know.

**Comment by AVGP** [comment]
I double checked and it's all done and dusted :)
