### ISSUE TITLE
Bug: New registrations fail with the error, "No usable value for emailOptIn Did not find value which can be converted into boolean"

### ISSUE THREAD

**Issue by itsbrianburton** [archilogic-com/3dio-website#105]
How to reproduce:
1. Go to https://3d.io/#pricing
2. Click on "Sign Up"
3. Enter any email address

Expected Result:
New account created

Actual Result:
Toast appears displaying the error, "No usable value for emailOptIn Did not find value which can be converted into boolean"

**Comment by frederic-schwarz** [comment]
thanks for the report. we'll fix this asap

**Comment by frederic-schwarz** [comment]
issue is fixed
