### ISSUE TITLE
Append link icons to h tags allowing to linking to those directly

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-website#22]
Like this:
![3d_io](https://user-images.githubusercontent.com/6619499/28569335-a9642bc4-7139-11e7-83ca-580d9d06d35e.jpg)

**Comment by troubalex** [comment]
@AVGP pointed me to this issue today. I should be able to sort this out.

How is this supposed to behave? Keep the link on the h tags and show the icon on hover? Or add an icon that has the link and remove that from the h tag itself?

My suggestion is to keep the link on the headlines, add the icon in a non-cluttering way, and give it a hover effect. That way it's discoverable but out of the way.

**Comment by AVGP** [comment]
That sounds good to me.

I think the original idea was to have a link icon next to the text so
people can use it to share a particular section, but your suggestion sounds
like great to me!

**Comment by troubalex** [comment]
Alright. I'll take a look.

**Comment by tomas-polach** [comment]
@troubalex you are totally right: a light hovering effect would be much more elegant and less obtrusive than adding icons everywhere!

**Comment by troubalex** [comment]
I'll come up with something nice. Which icon set are you using?
