### ISSUE TITLE
Changing size of  code/menu tab of app creator

### ISSUE THREAD

**Issue by david-tran-archilogic** [archilogic-com/3dio-website#38]
How to:
- Open app creator on windows with Chrome/Firefox
- Move your mouse cursor to the border of the code tab and drag it to the right side to make it bigger

Expected:
- You can make the tab bigger (actually works with MS Edge)

Actual Result in Chrome:
- Code tab jumps to the right border of the browser window filling up all the space.
- Same happens if you try to increase the size of the menu tab.
- 3D Window is not visible anymore
- You have to reload the browsertab to "fix" it

Actual Result in Firefox:
You can't increase the size of the code tab at all.

![image](https://user-images.githubusercontent.com/23555744/29661266-c813be4e-88c3-11e7-8dc3-84b135a868ed.png)

**Comment by tomas-polach** [comment]
thx! not a bug but a glitch though

**Comment by frederic-schwarz** [comment]
moved the issue to 3dio-app-creator repo
