### ISSUE TITLE
https://3d.io/floor-plan-to-3d-conversion.html links to not working https://io3d-floor-plan-app.herokuapp.com/

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-website#43]
go to 
https://3d.io/floor-plan-to-3d-conversion.html 

this links to 
https://io3d-floor-plan-app.herokuapp.com/

which is currently not working

suggest to linke to spaces.archilogic.com/order
till https://github.com/archilogic-com/3dio-floor-plan-app/issues/6 is resolved

**Comment by frederic-schwarz** [comment]
seems like a wrong API key was the issue and soon to be resolved

**Comment by m-ke** [comment]
Resolved now.
