### ISSUE TITLE
A second empty tab opens when contacting a Partner by e-mail

### ISSUE THREAD

**Issue by sjeftijssen** [archilogic-com/3dio-website#73]
Steps:
1. Go to any of the specific partner pages on 3d.io (e.g. Haus Virtual)
2. Click on the "email" button, or on the "Order for $xxxx+" button

Expect:
1. Expect to have a pop up window that allows to send an e-mail to the respective partner.

Actual:
1. You get the expect pop up, this is good.
2. There is a second empty tab that opens in the browser. This is not good

Should be adjusted so that only the pop-up appears and there is no second tab that opens.

**Comment by AVGP** [comment]
Doesn't happen on my laptop, btw

**Comment by sjeftijssen** [comment]
Chrome?

Asked @m-ke and she has the same issue.

**Comment by AVGP** [comment]
Chrome on OSX

2017-10-26 5:56 GMT-07:00 sjeftijssen <notifications@github.com>:

**Comment by tomas-polach** [comment]
is it ok if i take care of this?

**Comment by tomas-polach** [comment]
yep: the href tag has the `target="_blank"` attribute.
https://github.com/archilogic-com/3dio-website/blob/master/src/pug-common/partner-profile-page.pug#L24

**Comment by tomas-polach** [comment]
fixed in https://github.com/archilogic-com/3dio-website/commit/3f6969efbe805be34a0932959ab9d63858e8349e

**Comment by tomas-polach** [comment]
`target="_blank"` attribute still there o_O will have a look at this later...

**Comment by tomas-polach** [comment]
@sjeftijssen congrats! you fixed this one
