### ISSUE TITLE
Camera bookmark tour not working

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-website#87]
How to reproduce:
1. goto https://3d.io/use-case/designer-portfolio-augmented-vr.html
2. click on the play button of the example

Expected Result:
camera animates from bookmark to bookmark

Actual Result:
- camera starts on random position and remains stopped
- after clicking play button camera moves to first bookmark and remains there

**Comment by tomas-polach** [comment]
realized that showcase at https://3d.io/use-case/3d-app-with-lightmaps.html is also not working

**Comment by AVGP** [comment]
Ah, the problem was the liberal linking to a non-stable version of aframe-animations. I fixed it in all templates but not in the use cases.

**Comment by tomas-polach** [comment]
cool! thx. shall i open a new issue for the use cases?

**Comment by AVGP** [comment]
Nah, turns out only one remained affected and I fixed it while I was at it.
I also quickly went through the appmaker apps we've got in our account to fix the link where it was still pointing to the unstable version. Should be all good!

**Comment by tomas-polach** [comment]
perfect! THX!
